apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: nodejs-8-rhel7-angular
  name: nodejs-8-rhel7-angular
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: nodejs-8-rhel7-angular:latest
      namespace: krang
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/NicholasCostanzo/nodejs-8-rhel7-angular.git
    sourceSecret:
      name: gitsecret
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs-8-rhel7:latest
        namespace: krang
    type: Docker
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
